export const fullPresentationFixture = {
  client_id: "aup_01JPHASE1PRESENTATION",
  logical_client_id: "aup_01JPHASE1PRESENTATION",
  version: 1,
  workspace_id: "ws_01JWORKSPACE",
  title: "A faster way to find products",
  summary: "Search by SKU, article number, or customer.",
  status: "draft",
  presentation_type: "slide_page",
  category: "improvement",
  audience_mode: "all_matching",
  display_priority: 100,
  is_dismissible: true,
  starts_at: null,
  expires_at: null,
  published_at: null,
  archived_at: null,
  created_at: "2026-07-22T09:00:00+00:00",
  created_by_id: "usr_01JAUTHOR",
  updated_at: null,
  slides: [
    {
      client_id: "aups_01JSLIDE",
      sequence_order: 1,
      title: null,
      description: null,
      layout_type: "media_top",
      playback_mode: "timed",
      duration_ms: 8_000,
      composition_schema_version: 1,
      media: [],
      action: null,
      elements: [
        {
          client_id: null,
          element_type: "text",
          sequence_order: 0,
          layer_index: 10,
          start_ms: 0,
          end_ms: null,
          media: null,
          text_content: "Legacy synthesized headline",
          layout: { x: 0.08, y: 0.72, width: 0.84, height: 0.15, anchor: "center" },
          style: { text_role: "headline", text_align: "center", font_weight: 700 },
          enter_animation: { type: "fade_up", duration_ms: 350, easing: "ease_out" },
          exit_animation: null,
        },
      ],
    },
  ],
  audience: {
    audience_mode: "all_matching",
    app_keys: [],
    role_keys: [],
    workspace_ids: [],
    user_ids: [],
  },
} as const;

export const presentationListItemFixture = {
  client_id: fullPresentationFixture.client_id,
  logical_client_id: fullPresentationFixture.logical_client_id,
  version: fullPresentationFixture.version,
  workspace_id: fullPresentationFixture.workspace_id,
  title: fullPresentationFixture.title,
  summary: fullPresentationFixture.summary,
  status: fullPresentationFixture.status,
  presentation_type: fullPresentationFixture.presentation_type,
  category: fullPresentationFixture.category,
  audience_mode: fullPresentationFixture.audience_mode,
  display_priority: fullPresentationFixture.display_priority,
  is_dismissible: fullPresentationFixture.is_dismissible,
  starts_at: fullPresentationFixture.starts_at,
  expires_at: fullPresentationFixture.expires_at,
  published_at: fullPresentationFixture.published_at,
  archived_at: fullPresentationFixture.archived_at,
  created_at: fullPresentationFixture.created_at,
  created_by_id: fullPresentationFixture.created_by_id,
  updated_at: fullPresentationFixture.updated_at,
  slide_count: 3,
  media_kinds: ["image", "video"],
  cover_url: "https://cdn.example.com/presentation-cover.jpg",
} as const;

export function envelope<T>(data: T) {
  return { data, ok: true, warnings: [] } as const;
}
