export {
  UPHOLSTERY_CREATE_ORDER_SLIDE_ID,
  UPHOLSTERY_ORDER_DETAIL_SLIDE_ID,
  UPHOLSTERY_ORDERING_SLIDE_ID,
  UPHOLSTERY_RECEIVE_ORDER_SLIDE_ID,
  UPHOLSTERY_SHORTAGE_DETAIL_SLIDE_ID,
  upholsteryOrderingSurfaces,
} from "./surfaces";
